Player 1 Input:
  Handler: Evdev
  Device: 4. Microsoft X-Box 360 pad
  Config:
    Left Stick Left: LX-
    Left Stick Down: LY+
    Left Stick Right: LX+
    Left Stick Up: LY-
    Right Stick Left: RX-
    Right Stick Down: RY+
    Right Stick Right: RX+
    Right Stick Up: RY-
    Start: Start
    Select: Select
    PS Button: Mode
    Square: X
    Cross: A
    Circle: B
    Triangle: Y
    Left: Hat0 X-
    Down: Hat0 Y+
    Right: Hat0 X+
    Up: Hat0 Y-
    R1: TR
    R2: RZ+
    R3: Thumb R
    L1: TL
    L2: LZ+
    L3: Thumb L
    IR Nose: ""
    IR Tail: ""
    IR Left: ""
    IR Right: ""
    Tilt Left: ""
    Tilt Right: ""
    Motion Sensor X:
      Axis: X
      Mirrored: false
      Shift: 0
    Motion Sensor Y:
      Axis: Y
      Mirrored: false
      Shift: 0
    Motion Sensor Z:
      Axis: Z
      Mirrored: false
      Shift: 0
    Motion Sensor G:
      Axis: RY
      Mirrored: false
      Shift: 0
    Orientation Reset Button: ""
    Orientation Enabled: false
    Pressure Intensity Button: ""
    Pressure Intensity Percent: 50
    Pressure Intensity Toggle Mode: false
    Pressure Intensity Deadzone: 0
    Analog Limiter Button: ""
    Analog Limiter Toggle Mode: false
    Left Stick Multiplier: 100
    Right Stick Multiplier: 100
    Left Stick Deadzone: 30
    Right Stick Deadzone: 30
    Left Stick Anti-Deadzone: 33
    Right Stick Anti-Deadzone: 33
    Left Trigger Threshold: 0
    Right Trigger Threshold: 0
    Left Pad Squircling Factor: 8000
    Right Pad Squircling Factor: 8000
    Color Value R: 0
    Color Value G: 0
    Color Value B: 0
    Blink LED when battery is below 20%: true
    Use LED as a battery indicator: false
    LED battery indicator brightness: 50
    Player LED enabled: true
    Large Vibration Motor Multiplier: 100
    Small Vibration Motor Multiplier: 100
    Switch Vibration Motors: false
    Mouse Movement Mode: Relative
    Mouse Deadzone X Axis: 60
    Mouse Deadzone Y Axis: 60
    Mouse Acceleration X Axis: 200
    Mouse Acceleration Y Axis: 250
    Left Stick Lerp Factor: 100
    Right Stick Lerp Factor: 100
    Analog Button Lerp Factor: 100
    Trigger Lerp Factor: 100
    Device Class Type: 0
    Vendor ID: 1356
    Product ID: 616
  Buddy Device: ""
